location:
    source_directories:
        - ~/.config
        - ~/Code
        - ~/Documents
        - ~/Pictures
        - ~/Sync

    repositories:
        - ssh://q8730b51@q8730b51.repo.borgbase.com/./repo

storage:
    compression: lz4

retention:
    keep_daily: 7
    keep_weekly: 4
    keep_monthly: 6

consistency:
    checks:
        - repository
        - archives
    check_last: 3
