[packages]
dnf = [
  "git",
  "tmux",
  "zoxide",
  "eza",
  "htop",
  "bat",
  "git-delta",
  "syncthing",
  "distrobox",
  "fastfetch",
  "fuzzel",
  "waybar",
  "kanshi",
  "hyprlock",
  "hypridle",
  "gamescope",
  "cascadia-code-nf-fonts",
  "polkit-kde",
  "libinput-utils",
]

[copr]
repos = [
  "yalter/niri-git",
  "agriffis/neovim-nightly",
  "pgdev/ghostty",
  "markupstart/SwayOSD",
  "markupstart/xwayland-satellite"
]
packages = [
  "neovim",
  "ghostty",
  "niri",
  "swayosd",
  "xwayland-satellite"
]

[rpmfusion]
enable = true
packages = [
  "steam",
]

[flatpak]
repos = [

]
flathub = [
  "com.plexamp.Plexamp",
  "com.discordapp.Discord"
]
flathub_beta = [
  "com.yubico.yubioath"
]
