source_directories:
  - ~/.config
  - ~/Code
  - ~/Documents
  - ~/Pictures
  - ~/Sync
repositories:
    - path: ssh://q8730b51@q8730b51.repo.borgbase.com/./repo

storage:
  compression: lz4

keep_daily: 7
keep_weekly: 4
keep_monthly: 6

check_last: 3

unknown_unencrypted_repo_access_is_ok: true
