source_directories:
    - /home/evan/

repositories:
    - path: ssh://yc6kzjhm@yc6kzjhm.repo.borgbase.com/./repo
      label: borgbase-home-dir

patterns:
    # Specific exclusions only
    - '- /home/evan/.cache/**'
    - '- /home/evan/Downloads/**'
    - '- /home/evan/Code/**'
    - '- /home/evan/go/**'
    - '- /home/evan/.local/**'
    - '- /home/evan/.npm/**'
    - '- /home/evan/.config/emacs/**'
    - '- /home/evan/.opam/**'
    - '- /home/evan/.rustup/**'
    - '- /home/evan/.cargo/**'
    - '- /home/evan/.m2/**'
    - '- /home/evan/.gradle/**'
    - '- /home/evan/.wine/**'
    - '- /home/evan/snap/**'
    - '- /home/evan/.steam/**'
    - '- /home/evan/.steampath'
    - '- /home/evan/.steampid'
    - '- /home/evan/.nv/**'
    - '- /home/evan/.pki/**'
    - '- /home/evan/borg-mount/**'
    - '- /home/evan/.w3m/**'
    - '- /home/evan/Templates/**'
    - '- /home/evan/.thumbnails/**'
    - '- /home/evan/.mozilla/**'
    - '- /home/evan/.dots/**'
    - '- /home/evan/.xlcore/**'
    - '- /home/evan/.var/**'
    - '- /home/evan/.atuin/**'
    - '- /home/evan/.msmtp.log'
    - '- /home/evan/.lein/**'

encryption_passcommand: |
  sh -c 'gpg -q --for-your-eyes-only --no-tty -d ~/.authinfo.gpg 2>/dev/null | awk "{if (\$1==\"machine\" && \$2==\"www.borgbase.com\" && \$3==\"login\" && \$4==\"evan@evanriley.net\") print \$NF}"'

retention:
    keep_within: 3H
    keep_daily: 7
    keep_weekly: 4
    keep_monthly: 6
    keep_yearly: 1
